name = "elmar_crm"
main = "src/index.ts"
compatibility_date = "2025-08-26"
compatibility_flags = ["nodejs_compat"]

[durable_objects]
bindings = [{ name = "RATE_LIMIT", class_name = "RateLimiter" }]

[[migrations]]
tag = "v1"
new_classes = ["RateLimiter"]

[[d1_databases]]
binding = "ADMIN_DB"
database_name = "admin_db"
database_id = "f376f385-737f-4589-87db-53e16cd3ddaa"

[[d1_databases]]
binding = "TENANT_DB_elmar"
database_name = "elmar_crm"
database_id = "1b3f5d39-a2d7-4467-bab8-db02bd8fc910"

[[kv_namespaces]]
binding = "TENANT_CONFIGS"
id = "fa1a750bbefb4247b289a33fe4774b02"

[vars]
ACCOUNT_ID = "e389917ff47be3b722b6c3541b732926"
SENDGRID_API_URL = "https://api.sendgrid.com/v3/mail/send"

[triggers]
crons = ["*/5 * * * *"]